manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: v0.2
    - name: zmk-auto-layer
      remote: urob
      revision: v0.2
  self:
    path: config
