# Simple workflow for drawing the keymap and deploying static content to GitHub Pages
name: Draw keymap

on:
  - push

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "build-zmk"

jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - name: Cache west workspace
        uses: actions/cache@v4
        with:
          path: |
            .west
            zmk
            zephyr
            modules
          key: ${{ runner.os }}-west-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-west-
      - name: Init zephyr
        run: just init
      - name: Build files
        run: just build all

      - run: just draw
      - name: Commit updated images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "img/*.svg img/*.yaml"
          commit_message: updated kbd images

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "artifacts"
          path: |
            firmware/*.uf2
            img/corne.svg
