# Simple workflow for drawing the keymap and deploying static content to GitHub Pages
name: Draw keymap

on:
  workflow_dispatch: # can be triggered manually
  push:
    paths:
      - ".github/workflows/draw.yml"
      - "config/*.keymap"
      - "config/*.dtsi"
      - "keymap_drawer.config.yaml"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  draw:
    runs-on: ubuntu-latest
    outputs:
      drawings: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # So the reference to the parent commit is available when amending
          # See:
          # - https://github.com/stefanzweifel/git-auto-commit-action#using---amend-and---no-edit-as-commit-options
          # - https://github.com/stefanzweifel/git-auto-commit-action/issues/159#issuecomment-845347950
          # - https://github.com/actions/checkout
          fetch-depth: 2
          submodules: recursive

      - name: Install keymap-drawer (pypi)
        run: python3 -m pip install keymap-drawer

      - name: Draw keymaps
        id: draw
        run: |
          sudo apt-get install -y yq
          keymap -c "draw/config.yaml" parse -z "config/corne.keymap" >"draw/base.yaml"
          keymap -c "draw/config.yaml" draw "draw/base.yaml" >"draw/corne.svg"

      - name: Get last commit message
        id: last_commit_message
        run: |
          echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Commit updated images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "img/*.svg img/*.yaml"
          # So the previous commit is amended instead of creating a new one when desired
          # See:
          # - https://github.com/stefanzweifel/git-auto-commit-action#using---amend-and---no-edit-as-commit-options
          # - https://github.com/stefanzweifel/git-auto-commit-action/issues/159#issuecomment-845347950
          # - https://github.com/actions/checkout
          commit_message: "${{ steps.last_commit_message.outputs.msg }}"
          commit_options: "--amend --no-edit"
          push_options: "--force-with-lease"
          skip_fetch: true

      - name: Artifact upload
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: "keymap"
          path: |
            img/corne.svg
